[package]
name = "rustbigdata"
version = "0.1.0"
authors = ["Jefferson Marchetti <jefferson@contaswap.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "0.16.0"
rust-s3 = "0.11.0"